---
title: "Bosque tropical húmedo en Costa Rica"
description: |
  Principales clases
format:
  html:
    embed-resources: true
lang: es
execute: 
  echo: false
  include: false
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(easystats)
library(here)
library(janitor)
library(sf)
library(stars)
library(terra)
library(tidyterra)
library(gt)
library(gtExtras)
library(ggthemes)
library(ggtext)
library(cowplot)
library(crgeo)
```


# Principales clases de bosque tropical húmedo en Costa Rica

```{r}
cr <- cr_outline_c
```

```{r}
mc <- rast("cr_forests/cr_forest_main_classes.tif")
```

```{r}
mc <- mc |>
  crop(cr) |>
  mask(cr)
```

```{r}
#| message: false
#| warning: false
#| include: true
#| out-width: 100%
#| label: fig-mc_cr
#| fig-cap: Clases principales del bosque tropical húmedo de Costa Rica.
ggplot() +
  theme_void() +
  geom_spatraster(data = mc) +
  scale_fill_coltab(data = mc, name = "Tipo de \nBosque") +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 6, vjust = 0.1), 
    legend.key.width = unit(0.3, "cm"),
    legend.key.size = unit(0.1, "cm"),
    legend.key.spacing.y = unit(0.06, "cm")) +
  guides(fill = guide_legend(ncol = 3)) +
  theme(legend.key = element_rect(color = "black"))
```


# Subtipos de bosque tropical húmedo en Costa Rica

```{r}
cr <- cr_outline_c
```

```{r}
st <- rast("cr_forests/cr_forest_subtypes.tif")
```

```{r}
st <- st |>
  crop(cr) |>
  mask(cr)
```

```{r}
#| message: false
#| warning: false
#| include: true
#| out-width: 100%
#| label: fig-st_cr
#| fig-cap: Bosque tropical húmedo de Costa Rica.
ggplot() +
  theme_void() +
  geom_spatraster(data = st) +
  scale_fill_coltab(data = st, name = "Tipo de \nBosque") +
  theme(
    legend.text = element_text(size = 4, vjust = 0.1), 
    legend.position = "bottom",
    legend.key.width = unit(0.2, "cm"),
    legend.key.size = unit(0.05, "cm")) +
  guides(fill = guide_legend(ncol = 3)) +
  theme(legend.key = element_rect(color = "black"))
```

# Bosque tropical húmedo no alterado en Costa Rica

```{r}
ud <- rast("cr_forests/cr_forest_undisturbed_degraded.tif")
```

```{r}
ud
```

```{r}
#| message: false
#| warning: false
#| include: true
#| echo: false
#| out-width: 100%
#| label: fig-ud_cr
#| fig-cap: Bosque tropical húmedo no alterado de Costa Rica.
ggplot() +
  theme_minimal() +
  geom_spatraster(data = ud) +
  scale_fill_coltab(data = ud, name = "Tipo de Bosque")
```

# Cambio anual de bosque tropical húmedo en Costa Rica

```{r}
cr_ac_categorical <- rast("cr_forests/cr_annual_change_c.tif")
```

```{r}
colores_ac <- data.frame(value = c(1,2,3,4,5,6), col = c("#005a00", "#649b23", "#ff870f", "#d2fa3c", "#008cbe", "#ffffff"))
```

```{r}
coltab(cr_ac_categorical[[1]]) <- colores_ac
coltab(cr_ac_categorical[[2]]) <- colores_ac
coltab(cr_ac_categorical[[3]]) <- colores_ac
coltab(cr_ac_categorical[[4]]) <- colores_ac
coltab(cr_ac_categorical[[5]]) <- colores_ac
coltab(cr_ac_categorical[[6]]) <- colores_ac
coltab(cr_ac_categorical[[7]]) <- colores_ac
coltab(cr_ac_categorical[[8]]) <- colores_ac
coltab(cr_ac_categorical[[9]]) <- colores_ac
coltab(cr_ac_categorical[[10]]) <- colores_ac
coltab(cr_ac_categorical[[11]]) <- colores_ac
coltab(cr_ac_categorical[[12]]) <- colores_ac
coltab(cr_ac_categorical[[13]]) <- colores_ac
coltab(cr_ac_categorical[[14]]) <- colores_ac
coltab(cr_ac_categorical[[15]]) <- colores_ac
coltab(cr_ac_categorical[[16]]) <- colores_ac
coltab(cr_ac_categorical[[17]]) <- colores_ac
coltab(cr_ac_categorical[[18]]) <- colores_ac
coltab(cr_ac_categorical[[19]]) <- colores_ac
coltab(cr_ac_categorical[[20]]) <- colores_ac
coltab(cr_ac_categorical[[21]]) <- colores_ac
coltab(cr_ac_categorical[[22]]) <- colores_ac
coltab(cr_ac_categorical[[23]]) <- colores_ac
coltab(cr_ac_categorical[[24]]) <- colores_ac
coltab(cr_ac_categorical[[25]]) <- colores_ac
coltab(cr_ac_categorical[[26]]) <- colores_ac
coltab(cr_ac_categorical[[27]]) <- colores_ac
coltab(cr_ac_categorical[[28]]) <- colores_ac
coltab(cr_ac_categorical[[29]]) <- colores_ac
coltab(cr_ac_categorical[[30]]) <- colores_ac
coltab(cr_ac_categorical[[31]]) <- colores_ac
coltab(cr_ac_categorical[[32]]) <- colores_ac
coltab(cr_ac_categorical[[33]]) <- colores_ac
coltab(cr_ac_categorical[[34]]) <- colores_ac
```

```{r}
r_01 <- subset(cr_ac_categorical, c(1:17))
r_02 <- subset(cr_ac_categorical, c(18:34))
```

```{r}
#| message: false
#| warning: false
#| include: true
#| out-width: 100%
#| label: fig-ac_cr_01
#| fig-cap: Cambio anual del bosque tropical húmedo de Costa Rica.
ggplot() +
  theme_void() +
  geom_spatraster(data = r_01) +
  facet_wrap(~ lyr, ncol = 5) +
  scale_fill_coltab(data = r_01, name = "Tipo de Bosque") +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 7,vjust = 0.1), 
    legend.key.width = unit(0.3, "cm"),
    legend.key.height = unit(0.2, "cm"),
    legend.key.spacing.y = unit(0.04, "cm")) +
  guides(fill = guide_legend(ncol = 3)) +

  theme(
    strip.background = element_blank(),
    strip.text.x = element_textbox(
      size = 6,
      color = "white",
      fill = "#B71234", 
      box.color = "#B71234",
      halign = 0.5, 
      linetype = 1, 
      r = unit(3, "pt"), 
      width = unit(0.8, "npc"),
      padding = margin(1, 0, 1, 0), 
      margin = margin(2, 2, 2, 2))) +
  theme(legend.key = element_rect(color = "black"))
```

```{r}
#| message: false
#| warning: false
#| include: true
#| out-width: 100%
#| label: fig-ac_cr_02
#| fig-cap: Cambio anual del bosque tropical húmedo de Costa Rica.
ggplot() +
  theme_void() +
  geom_spatraster(data = r_02) +
  facet_wrap(~ lyr, ncol = 5) +
  scale_fill_coltab(data = r_02, name = "Tipo de Bosque") +
  theme(
    legend.position = "bottom",
    legend.text = element_text(size = 7,vjust = 0.1), 
    legend.key.width = unit(0.3, "cm"),
    legend.key.height = unit(0.2, "cm"),
    legend.key.spacing.y = unit(0.04, "cm")) +
  guides(fill = guide_legend(ncol = 3)) +

  theme(
    strip.background = element_blank(),
    strip.text.x = element_textbox(
      size = 6,
      color = "white",
      fill = "#B71234", 
      box.color = "#B71234",
      halign = 0.5, 
      linetype = 1, 
      r = unit(3, "pt"), 
      width = unit(0.8, "npc"),
      padding = margin(1, 0, 1, 0), 
      margin = margin(2, 2, 2, 2))) +
  theme(legend.key = element_rect(color = "black"))
```

```{r}
ac_numbers <- data_read("cr_forests/JRC_TMF_EvolutionChanges_1990_2023_vAugust2024.csv") |>
  mutate_if(is.character, as.factor) |>
  clean_names()
```

```{r}
cr_ac_numbers <- ac_numbers |>
  filter(country == "Costa Rica")
```

```{r}
names(cr_ac_numbers)
```

```{r}
summary(cr_ac_numbers)
```

```{r}
#| message: false
#| warning: false
#| include: true
ggplot(cr_ac_numbers, aes(year, undisturbed_tmf)) +
  theme_minimal() +
  geom_line(color = "dodgerblue") +
  geom_point(color = "dodgerblue") +
  ylab("Area de bosques no perturbados (Mha)") +
  xlab("Año")
```

```{r}
#| message: false
#| warning: false
#| include: true
ggplot(cr_ac_numbers, aes(year, total_forest_disturbances_degradation_or_deforestation)) +
  theme_minimal() +
  geom_line(color = "dodgerblue") +
  geom_point(color = "dodgerblue") +
  ylab("Area de bosque degradado o deforestado (Mha)") +
  xlab("Año")
```




